'use server';
/**
 * @fileOverview An AI-powered assistant to answer user questions about CourseVerse.
 *
 * - faqAssistant - A function that takes a user's question and finds the best answer.
 * - FaqAssistantInput - The input type for the faqAssistant function.
 * - FaqAssistantOutput - The return type for the faqAssistant function.
 */

import { ai } from '@/ai/genkit';
import { z } from 'genkit';

// The static list of FAQs the AI will use as its primary knowledge base.
const PREDEFINED_FAQS = [
    {
      id: 'what-is-courseverse',
      question: 'What is CourseVerse and how does it work?',
      answer:
        'CourseVerse is a distribution platform for high-quality, licensed educational content. As the administrator, I manage the platform and ensure access to courses created by trusted third-party experts. It is not a marketplace for instructors to upload their own content.',
    },
    {
      id: 'are-courses-licensed',
      question: 'Are CourseVerse courses officially licensed?',
      answer:
        'Yes. Every course available on CourseVerse is officially licensed from its original creator. We believe in ethical content distribution and compensating creators for their work.',
    },
    {
      id: 'lifetime-access',
      question: 'Do I get lifetime access after purchase?',
      answer:
        'Yes, once a course is purchased, you have lifetime access to its downloadable materials through your dashboard. You can download them as many times as you like.',
    },
    {
      id: 'payment-verification',
      question: 'How does the payment and verification process work?',
      answer:
        'You pay the specified amount via UPI. After payment, you submit the transaction ID (UTR) and a screenshot on the payment page. Our automated system, enhanced with AI, verifies the payment. For valid payments, course access is granted instantly.',
    },
    {
      id: 'after-purchase',
      question: 'What happens after I buy a course?',
      answer:
        'Once your payment is verified, the course is immediately added to your account. You will have access to download all the course materials, including videos and project files, directly from your dashboard.',
    },
    {
      id: 'where-to-download',
      question: 'Where can I download my purchased courses?',
      answer:
        'All your purchased courses and their downloadable assets are available in the "My Downloads" section of your personal dashboard. You must be logged in to access this page.',
    },
    {
      id: 'are-certificates-provided',
      question: 'Are certificates provided?',
      answer:
        'Yes, upon successful completion of a course, you will be issued a verifiable certificate which you can find in your dashboard.',
    },
    {
      id: 'payment-issue',
      question: 'What should I do if I face a payment issue?',
      answer:
        'If your payment is successful but verification fails, or if you encounter any other issues, please contact us through the contact page. We will manually review your transaction and resolve the issue as quickly as possible.',
    },
     {
      id: 'login-required',
      question: 'Is login required to access downloads?',
      answer:
        'Yes, you must be logged into your CourseVerse account to access the "My Downloads" page and download your purchased course materials. This ensures secure access to your content.',
    },
];

const FaqAssistantInputSchema = z.object({
  userQuestion: z.string().describe("The user's question about CourseVerse."),
});
export type FaqAssistantInput = z.infer<typeof FaqAssistantInputSchema>;

const FaqAssistantOutputSchema = z.object({
  bestMatchId: z.string().optional().describe('The ID of the best matching predefined FAQ. If no good match is found, this can be empty.'),
  answer: z.string().describe("A clear, concise answer to the user's question. If no relevant answer can be found or generated, state that you cannot answer."),
  isGenerated: z.boolean().describe('Set to true if the answer was generated by the AI, and false if it came directly from the predefined list.'),
});
export type FaqAssistantOutput = z.infer<typeof FaqAssistantOutputSchema>;

export async function faqAssistant(input: FaqAssistantInput): Promise<FaqAssistantOutput> {
  return faqAssistantFlow(input);
}

const prompt = ai.definePrompt({
  name: 'faqAssistantPrompt',
  input: { schema: z.object({
    userQuestion: z.string(),
    PREDEFINED_FAQS: z.any(),
  }) },
  output: { schema: FaqAssistantOutputSchema },
  prompt: `You are a helpful assistant for a learning platform called CourseVerse. Your goal is to answer user questions accurately based on a predefined list of Frequently Asked Questions.

Here is the knowledge base of predefined FAQs (in JSON format):
{{{json PREDEFINED_FAQS}}}

The user's question is: "{{{userQuestion}}}"

Your task is to find the single best matching FAQ from the knowledge base.
1.  Analyze the user's question and compare it against the "question" field of each FAQ in the list.
2.  If you find a strong match (the user is asking about the same topic), set 'bestMatchId' to the 'id' of that FAQ, set 'answer' to the corresponding 'answer' from the knowledge base, and set 'isGenerated' to false.
3.  If there is NO strong match, you must generate a new answer. The generated answer MUST be based on the context provided in the *entire* list of FAQs. Do not make up information.
    - If you can generate a confident answer, provide it in the 'answer' field and set 'isGenerated' to true. Do not set 'bestMatchId'.
    - If you cannot answer the question based on the provided FAQs, your answer MUST be: "I'm sorry, I don't have enough information to answer that question. Please try rephrasing or contact support for more help." and set 'isGenerated' to true.
4.  Your response MUST be a valid JSON object matching the output schema.

Platform Rules for Answer Generation:
- CourseVerse is a course distribution platform, not a school.
- The platform administrator (Avik) manages content but does not teach.
- All courses are licensed from third parties.
- Certificates are for "completion," not official accreditation.
- Payments are verified via a UTR/screenshot system.
- Lifetime access is for downloadable materials.
`,
});

const faqAssistantFlow = ai.defineFlow(
  {
    name: 'faqAssistantFlow',
    inputSchema: FaqAssistantInputSchema,
    outputSchema: FaqAssistantOutputSchema,
  },
  async (input) => {
    // Add the predefined FAQs to the prompt's context.
    const { output } = await prompt({
      userQuestion: input.userQuestion,
      PREDEFINED_FAQS: PREDEFINED_FAQS, // Pass the array to the prompt
    });
    return output!;
  }
);
