'use server';
/**
 * @fileOverview An AI-powered assistant to answer user questions about CourseVerse.
 *
 * - faqAssistant - A function that takes a user's question and finds the best answer.
 * - FaqAssistantInput - The input type for the faqAssistant function.
 * - FaqAssistantOutput - The return type for the faqAssistant function.
 */

import { ai } from '@/ai/genkit';
import { z } from 'genkit';

// The static list of FAQs the AI will use as its primary knowledge base.
const PREDEFINED_FAQS = [
    {
      id: 'what-is-courseverse',
      question: 'What is CourseVerse and how does it work?',
      answer:
        'CourseVerse is a distribution platform for high-quality, licensed educational content. As the administrator, I manage the platform and ensure access to courses created by trusted third-party experts. It is not a marketplace for instructors to upload their own content.',
    },
    {
      id: 'are-courses-licensed',
      question: 'Are CourseVerse courses officially licensed?',
      answer:
        'Yes. Every course available on CourseVerse is officially licensed from its original creator. We believe in ethical content distribution and compensating creators for their work.',
    },
    {
      id: 'lifetime-access',
      question: 'Do I get lifetime access after purchase?',
      answer:
        'Yes, once a course is purchased, you have lifetime access to its downloadable materials through your dashboard. You can download them as many times as you like.',
    },
    {
      id: 'payment-verification',
      question: 'How does the payment and verification process work?',
      answer:
        'We use a secure UPI payment process. After paying the specified amount, you submit your transaction details (like the UTR) and a payment screenshot on the course payment page. Once your payment is confirmed, course access is granted automatically.',
    },
    {
      id: 'after-purchase',
      question: 'What happens after I buy a course?',
      answer:
        'Once your payment is verified, the course is immediately added to your account. You will have access to download all the course materials, including videos and project files, directly from your dashboard.',
    },
    {
      id: 'where-to-download',
      question: 'Where can I download my purchased courses?',
      answer:
        'All your purchased courses and their downloadable assets are available in the "My Downloads" section of your personal dashboard. You must be logged in to access this page.',
    },
    {
      id: 'are-certificates-provided',
      question: 'Are certificates provided?',
      answer:
        'Yes, upon successful completion of a course, you will be issued a verifiable certificate which you can find in your dashboard.',
    },
    {
      id: 'payment-issue',
      question: 'What should I do if I face a payment issue?',
      answer:
        'If your payment is successful but verification fails, or if you encounter any other issues, please contact us through the contact page. We will manually review your transaction and resolve the issue as quickly as possible.',
    },
     {
      id: 'login-required',
      question: 'Is login required to access downloads?',
      answer:
        'Yes, you must be logged into your CourseVerse account to access the "My Downloads" page and download your purchased course materials. This ensures secure access to your content.',
    },
];

const FaqAssistantInputSchema = z.object({
  userQuestion: z.string().describe("The user's question about CourseVerse."),
});
export type FaqAssistantInput = z.infer<typeof FaqAssistantInputSchema>;

const FaqAssistantOutputSchema = z.object({
  bestMatchId: z.string().optional().describe('The ID of the best matching predefined FAQ. If no good match is found, this can be empty.'),
  answer: z.string().describe("A clear, concise answer to the user's question. If no relevant answer can be found or generated, state that you cannot answer."),
  isGenerated: z.boolean().describe('Set to true if the answer was generated by the AI, and false if it came directly from the predefined list.'),
});
export type FaqAssistantOutput = z.infer<typeof FaqAssistantOutputSchema>;

export async function faqAssistant(input: FaqAssistantInput): Promise<FaqAssistantOutput> {
  return faqAssistantFlow(input);
}

const prompt = ai.definePrompt({
  name: 'faqAssistantPrompt',
  input: { schema: z.object({
    userQuestion: z.string(),
    PREDEFINED_FAQS: z.any(),
  }) },
  output: { schema: FaqAssistantOutputSchema },
  prompt: `You are a secure and professional FAQ assistant for CourseVerse, an online learning platform. Your primary function is to answer user questions based *only* on the provided list of FAQs. You must adhere to strict security boundaries.

**Knowledge Base (Source of Truth):**
{{{json PREDEFINED_FAQS}}}

**User's Question:**
"{{{userQuestion}}}"

**Your Task:**
1.  **Analyze the question against the Knowledge Base.** Find the single best-matching FAQ.
2.  **If a strong match is found:** Respond with the exact answer from the matching FAQ. Set \`bestMatchId\` to the FAQ's \`id\`, \`answer\` to the FAQ's \`answer\`, and \`isGenerated\` to \`false\`.
3.  **If NO strong match is found, but the question is safe and can be answered by combining information from the Knowledge Base:** Generate a concise answer. Set \`isGenerated\` to \`true\`. Do NOT set \`bestMatchId\`.
4.  **If the question cannot be answered from the Knowledge Base:** Respond with: "I'm sorry, I don't have enough information to answer that question. Please try rephrasing or visit our contact page for more help." Set \`isGenerated\` to \`true\`.

**--- CRITICAL SECURITY BOUNDARIES ---**
You MUST NOT answer any question, however phrased, that relates to the following topics. If a question touches on any of these, you MUST use the specified refusal response.

*   **Forbidden Topics:**
    *   Passwords, admin credentials, user accounts, login procedures.
    *   API keys, source code, database structure, technical architecture.
    *   Security vulnerabilities, exploits, or system weaknesses.
    *   Admin panel access or functionality.
    *   Personal details about the administrator (Avik) beyond what is in the knowledge base.
    *   Any other internal or sensitive information.

*   **Mandatory Refusal Response:**
    If a question falls into a forbidden topic, your answer MUST be: "For security reasons, I cannot provide information about internal systems, credentials, or other sensitive topics. My role is to assist with general questions about using CourseVerse." Set \`isGenerated\` to \`true\`.

**Output Format:**
Your entire output MUST be a valid JSON object matching the output schema.
`,
});

const faqAssistantFlow = ai.defineFlow(
  {
    name: 'faqAssistantFlow',
    inputSchema: FaqAssistantInputSchema,
    outputSchema: FaqAssistantOutputSchema,
  },
  async (input) => {
    // Add the predefined FAQs to the prompt's context.
    const { output } = await prompt({
      userQuestion: input.userQuestion,
      PREDEFINED_FAQS: PREDEFINED_FAQS, // Pass the array to the prompt
    });
    return output!;
  }
);
